[package]
name = "solidity"
version = "0.1.0"
authors = ["Nirvan Tyagi <nirvan.tyagi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
ark-ec = { version = "0.3" }
ark-std = { version = "0.3" }
ark-bn254 = { version = "0.3", features = [ "curve" ] }

ethabi = "16.0.0"
primitive-types = { version = "0.10", features = ["rlp"] }
hex = { version = "0.4" }
rand = { version = "0.8" }
sha3 = { version = "0.9" }

solidity_test_utils = { path = "../solidity_test_utils" }
range_proofs = { path = "../range_proofs" }
rsa = { path = "../rsa" }

[[bench]]
name = "bulletproofs_verifier"
path = "benches/bulletproofs_verifier.rs"
harness = false